### ISSUE TITLE
ImportError: No module named 'dictionary'

### ISSUE THREAD

**Issue by ChameleonRed** [studio-ousia/wikipedia2vec#3]
>>> from wikipedia2vec import Wikipedia2Vec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\root\Python35\lib\site-packages\wikipedia2vec\__init__.py", line 7, in <module>
    from dictionary import Dictionary
ImportError: No module named 'dictionary'

**Comment by ikuyamada** [comment]
This issue should be fixed in the newest Wikipedia2Vec package on PyPI.
